version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
